CREATE TABLE doacoes (
                         id_doacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         id_doador BIGINT NOT NULL,
                         data_doacao DATE NOT NULL,
                         valor DECIMAL(10,2),
                         tipo VARCHAR(20) NOT NULL,
                         descricao VARCHAR(500)
);

-- Inserindo 15 registros para testar a paginação (size=5)
INSERT INTO doacoes (id_doador, data_doacao, valor, tipo, descricao) VALUES
                                                                         (1, '2026-01-15', 150.00, 'FINANCEIRA', 'Doação mensal'),
                                                                         (2, '2026-02-10', 50.00, 'ALIMENTO', 'Cestas básicas'),
                                                                         (1, '2026-03-05', 200.00, 'FINANCEIRA', 'Campanha de inverno'),
                                                                         (3, '2026-04-12', 30.00, 'ROUPA', 'Casacos e cobertores'),
                                                                         (2, '2026-05-20', 100.00, 'ALIMENTO', 'Arroz e feijão'),
                                                                         (1, '2026-06-18', 500.00, 'FINANCEIRA', 'Doação empresa X'),
                                                                         (4, '2026-07-01', 40.00, 'ALIMENTO', 'Óleo e macarrão'),
                                                                         (3, '2026-07-15', 25.00, 'ROUPA', 'Calças jeans'),
                                                                         (2, '2026-08-05', 80.00, 'ALIMENTO', 'Leite em pó'),
                                                                         (1, '2026-08-10', 300.00, 'FINANCEIRA', 'Pagamento de conta de luz'),
                                                                         (4, '2026-08-15', 60.00, 'ALIMENTO', 'Fraldas geriátricas'),
                                                                         (3, '2026-08-20', 15.00, 'ROUPA', 'Camisetas infantis'),
                                                                         (2, '2026-08-22', 90.00, 'ALIMENTO', 'Café e açúcar'),
                                                                         (1, '2026-08-25', 1000.00, 'FINANCEIRA', 'Doação anonimada'),
                                                                         (4, '2026-08-28', 45.00, 'ALIMENTO', 'Produtos de higiene');